### ISSUE TITLE
iOS 12.1 black screen / app crash

### ISSUE THREAD

**Issue by msudol** [emcniece/cordova-plugin-rssi#2]
Still trying to debug what might be causing it, on an iPad.  Android working fine, need to get an older iOS device to do some additional troubleshooting, just thought I would give you a heads up. 

Using plugin version 1.1.0 from NPM. I'm not getting any error messages, I'll inform you as soon as I find something more tangible. As of right now it looks like the plugin is crashing the app.

**Comment by emcniece** [comment]
Great news - this is reproducible via iOS Simulator!

[RSSI.swift line 64](https://github.com/emcniece/cordova-plugin-rssi/blob/master/src/ios/RSSI.swift#L64): 

> Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

Looks like the device version extraction logic needs some additional type safety to allow for iPad version strings.

This shouldn't take too long to fix, but my week is packed. What kind of delivery time constraints are you working with?

**Comment by msudol** [comment]
we'll make due for a little bit, whatever suits your schedule.

**Comment by msudol** [comment]
just following up, have an idea about when you might get into this one?  thanks..

**Comment by emcniece** [comment]
@msudol I just released [v1.1.1](https://github.com/emcniece/cordova-plugin-rssi/releases/tag/1.1.1) which prevents the iPad crash.

There's a larger problem though - [iPad doesn't seem to report RSSI](https://github.com/emcniece/cordova-plugin-rssi/issues/3) through the native API the same way other iOS devices do. There is also very little documentation for this, so I will have to spend more time debugging to see if iPad compatibility is even possible.

**Comment by msudol** [comment]
seems to be working for my iPad at the moment, interesting though...  waiting for Santa to bring me a mac so I can start dabbling in swift myself.
