### ISSUE TITLE
Error making build recently, might be a dependency issue

### ISSUE THREAD

**Issue by msudol** [emcniece/cordova-plugin-rssi#6]
I got this error on a recent attempt to build. 

`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-rssi@^1.1.1" via npm 
Installing "cordova-plugin-rssi" at "1.1.1" for ios Failed to install 'cordova-plugin-rssi': 
CordovaError: Version of installed plugin: "cordova-plugin-add-swift-support@2.0.1" 
does not satisfy dependency plugin requirement "cordova-plugin-add-swift-support@^1.7.2". 
Try --force to use installed plugin as dependency. 
at /usr/local/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:557:37 
at _fulfilled (/usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54) 
at /usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:816:30 
at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:749:13) 
at /usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:509:49 
at flush (/usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:108:17) 
at process.internalTickCallback (internal/process/next_tick.js:70:11) 
Version of installed plugin: "cordova-plugin-add-swift-support@2.0.1" 
does not satisfy dependency plugin requirement "cordova-plugin-add-swift-support@^1.7.2". `

Can't figure out how to resolve without an update on this plugin?

**Comment by emcniece** [comment]
I see your [PR](https://github.com/emcniece/cordova-plugin-rssi/pull/5), thanks for submitting.

It looks like the issue here is that `cordova-plugin-rssi` requires major version 1 of `cordova-plugin-add-swift-support`, while you have major version 2 installed. What other plugin do you have that lists `cordova-plugin-add-swift-support@2.0.1` as a dependency?

**Comment by msudol** [comment]
I'll have to dive in and find out, I use phonegap build online these days so the build process is in the cloud..  my plugin list is pretty basic.  

    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-camera" spec="^4.0.3" />
    <plugin name="cordova-plugin-media-capture" spec="^3.0.2" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-fullscreen" spec="^1.2.0" />
    <plugin name="cordova-plugin-qrscanner" spec="^2.6.0" />
    <plugin name="cordova-plugin-rssi" spec="^1.1.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-globalization" source="npm" />
    <plugin name="cordova-plugin-dialogs" spec="^2.0.1" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />

I think I may have a solution, I'll dial them all back to hard spec instead of latest and see if that resolves anything.

**Comment by emcniece** [comment]
The troubleshooting assistance is much appreciated. Ideally this plugin should test the new `cordova-plugin-add-swift-support@2.0.1` and make a new release anyway... I'll get on that.

**Comment by msudol** [comment]
i think the culprit might be cordova-plugin-qrscanner's latest version 3.0.1 - it's plugin xml has
 <dependency id="cordova-plugin-add-swift-support" spec="~1.7.2" />

**Comment by emcniece** [comment]
Published https://www.npmjs.com/package/cordova-plugin-rssi version `1.1.2` which includes `cordova-plugin-add-swift-support@2.0.1`. Please try updating this plugin, and let me know what happens!

**Comment by msudol** [comment]
it's working well now thanks so much!
